// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiQrg-BCgrdJ_3rEfXm45YIerueYjM8FY',
    appId: '1:201287758741:web:74fca060049a88d296bc9c',
    messagingSenderId: '201287758741',
    projectId: 'moisil-proto',
    authDomain: 'moisil-proto.firebaseapp.com',
    storageBucket: 'moisil-proto.firebasestorage.app',
    measurementId: 'G-8X77WENQ8N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHvriFFNxliJ6mD3momq0FDAhzBNuL1Ko',
    appId: '1:201287758741:android:8b0041278ea7107e96bc9c',
    messagingSenderId: '201287758741',
    projectId: 'moisil-proto',
    storageBucket: 'moisil-proto.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3NJWExwu2pw36S08PM_wTOTW1kS5miM4',
    appId: '1:201287758741:ios:9599f673b171a12596bc9c',
    messagingSenderId: '201287758741',
    projectId: 'moisil-proto',
    storageBucket: 'moisil-proto.firebasestorage.app',
    iosBundleId: 'com.example.moisilFinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3NJWExwu2pw36S08PM_wTOTW1kS5miM4',
    appId: '1:201287758741:ios:9599f673b171a12596bc9c',
    messagingSenderId: '201287758741',
    projectId: 'moisil-proto',
    storageBucket: 'moisil-proto.firebasestorage.app',
    iosBundleId: 'com.example.moisilFinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiQrg-BCgrdJ_3rEfXm45YIerueYjM8FY',
    appId: '1:201287758741:web:fe9944c4d4b4256896bc9c',
    messagingSenderId: '201287758741',
    projectId: 'moisil-proto',
    authDomain: 'moisil-proto.firebaseapp.com',
    storageBucket: 'moisil-proto.firebasestorage.app',
    measurementId: 'G-T12HRB527E',
  );
}
